algoritmo "DobroeoTriplo"
// Autor : Maria Isadora C. Baeza
// Data : 29/03/2022
// Seção de Declarações: Calcula o dobro e o triplo de um numero
var
numero,resultdobro,resulttriplo:real

inicio
// entrada
escreval("Digite um número")
leia(numero)

//processamento
resultdobro<-(numero*2)
resulttriplo<-(numero*3)

//saída
escreval("Seu dobro foi de:",resultdobro)
escreval("Seu triplo foi de:",resulttriplo)

fimalgoritmo
